; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.31101.0 

	TITLE	c:\Users\super\documents\visual studio 2013\Projects\123\123\Source.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	_main
PUBLIC	??_C@_07PDOJDHMO@?$KJm?$KGW?5?3?6?$AA@		; `string'
PUBLIC	??_C@_07PKGDDDMN@?$LA?j?$KE?e?5?3?6?$AA@	; `string'
PUBLIC	??_C@_07LMJNCIPD@?$LM?F?$LO?G?5?3?6?$AA@	; `string'
PUBLIC	??_C@_07MJOHHMIE@?$KN?$FO?$KE?e?5?3?6?$AA@	; `string'
PUBLIC	??_C@_05PDJBBECF@pause?$AA@			; `string'
EXTRN	__imp__printf:PROC
EXTRN	__imp__system:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
;	COMDAT ??_C@_05PDJBBECF@pause?$AA@
CONST	SEGMENT
??_C@_05PDJBBECF@pause?$AA@ DB 'pause', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_07MJOHHMIE@?$KN?$FO?$KE?e?5?3?6?$AA@
CONST	SEGMENT
??_C@_07MJOHHMIE@?$KN?$FO?$KE?e?5?3?6?$AA@ DB 0adH, '^', 0a4H, 0e5H, ' :', 0aH
	DB	00H						; `string'
CONST	ENDS
;	COMDAT ??_C@_07LMJNCIPD@?$LM?F?$LO?G?5?3?6?$AA@
CONST	SEGMENT
??_C@_07LMJNCIPD@?$LM?F?$LO?G?5?3?6?$AA@ DB 0bcH, 0c6H, 0beH, 0c7H, ' :', 0aH
	DB	00H						; `string'
CONST	ENDS
;	COMDAT ??_C@_07PKGDDDMN@?$LA?j?$KE?e?5?3?6?$AA@
CONST	SEGMENT
??_C@_07PKGDDDMN@?$LA?j?$KE?e?5?3?6?$AA@ DB 0b0H, 0eaH, 0a4H, 0e5H, ' :', 0aH
	DB	00H						; `string'
CONST	ENDS
;	COMDAT ??_C@_07PDOJDHMO@?$KJm?$KGW?5?3?6?$AA@
CONST	SEGMENT
??_C@_07PDOJDHMO@?$KJm?$KGW?5?3?6?$AA@ DB 0a9H, 'm', 0a6H, 'W :', 0aH, 00H ; `string'
CONST	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT _main
_TEXT	SEGMENT
_i$ = -8						; size = 4
_main	PROC						; COMDAT
; File c:\users\super\documents\visual studio 2013\projects\123\123\source.cpp
; Line 5
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 7
	mov	DWORD PTR _i$[ebp], 0
	jmp	SHORT $LN7@main
$LN6@main:
	mov	eax, DWORD PTR _i$[ebp]
	add	eax, 1
	mov	DWORD PTR _i$[ebp], eax
$LN7@main:
	cmp	DWORD PTR _i$[ebp], 4
	jge	SHORT $LN5@main
; Line 9
	cmp	DWORD PTR _i$[ebp], 0
	jne	SHORT $LN4@main
; Line 11
	mov	esi, esp
	push	OFFSET ??_C@_07PDOJDHMO@?$KJm?$KGW?5?3?6?$AA@
	call	DWORD PTR __imp__printf
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN4@main:
; Line 13
	cmp	DWORD PTR _i$[ebp], 1
	jne	SHORT $LN3@main
; Line 15
	mov	esi, esp
	push	OFFSET ??_C@_07PKGDDDMN@?$LA?j?$KE?e?5?3?6?$AA@
	call	DWORD PTR __imp__printf
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN3@main:
; Line 17
	cmp	DWORD PTR _i$[ebp], 2
	jne	SHORT $LN2@main
; Line 19
	mov	esi, esp
	push	OFFSET ??_C@_07LMJNCIPD@?$LM?F?$LO?G?5?3?6?$AA@
	call	DWORD PTR __imp__printf
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN2@main:
; Line 21
	cmp	DWORD PTR _i$[ebp], 3
	jne	SHORT $LN1@main
; Line 23
	mov	esi, esp
	push	OFFSET ??_C@_07MJOHHMIE@?$KN?$FO?$KE?e?5?3?6?$AA@
	call	DWORD PTR __imp__printf
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN1@main:
; Line 25
	jmp	$LN6@main
$LN5@main:
; Line 26
	mov	esi, esp
	push	OFFSET ??_C@_05PDJBBECF@pause?$AA@
	call	DWORD PTR __imp__system
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 27
	xor	eax, eax
; Line 28
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
